class_name BriefingView
extends ShiftScreenView
## Pre-shift briefing (spec section 16), rebuilt on ShiftScreenView.
##
## The old version was a flat stack of default Labels: a 34px title, then
## every section as plain text, on a dim rectangle. It carried the right
## information but gave the player no way to see at a glance what kind of
## shift they were walking into -- and it was the first thing seen every
## shift, while the rest of the game had long since moved onto UiTheme.
##
## What's new beyond the styling: an operational summary in headline
## tiles, a KEY RISKS section and a RECOMMENDED ACTIONS section (both
## generated by ShiftAdvisor from real tracked state, not written flavour
## text), and a town-conditions readout drawn as meters instead of a raw
## numbers line. The interactive parts -- priorities, patrol tasking,
## reserve -- keep exactly the same behaviour and Commands calls they
## always had.

signal confirmed

const MAX_PRIORITIES := 3

var _world: WorldMapData
var _shift_number: int
var _priority_buttons: Dictionary = {} # option text -> Button
var _selected_priorities: Array[String] = []
var _patrol_pickers: Dictionary = {} # unit_id -> OptionButton
var _reserve_spinbox: SpinBox

func setup(world: WorldMapData, shift_number: int) -> void:
	_world = world
	_shift_number = shift_number
	build_frame()

	_add_hero()
	_add_summary_section()
	_add_risks_section()
	_add_recommendations_section()
	_add_conditions_section()
	_add_intelligence_section()
	_add_priorities_section()
	_add_patrol_section()
	_add_reserve_section()
	add_primary_button("CONFIRM SHIFT PLAN", _on_confirm_pressed)

func _add_hero() -> void:
	var core: SimulationCore = Simulation.core
	var shift: ShiftState = core.shift_manager.shift_state
	var season: GameEnums.Season = core.current_season()
	var is_night: bool = DutyPattern.is_night_shift(_shift_number)
	var chips: Array[Dictionary] = [
		{"text": "%s SHIFT" % DutyPattern.label(_shift_number).to_upper(),
			"color": Color(0.55, 0.70, 1.0) if is_night else Color(0.95, 0.80, 0.45)},
		{"text": "%s - %s" % [TimeFormat.clock(shift.shift_start_minute), TimeFormat.clock(shift.shift_end_minute)],
			"color": UiTheme.TEXT_DIM},
		{"text": SeasonCycle.label(season).to_upper(), "color": Color(0.55, 0.85, 0.55)},
		{"text": core.weather_manager.weather_text().to_upper(),
			"color": Color(0.60, 0.75, 0.95) if core.weather_manager.is_adverse() else UiTheme.TEXT_DIM},
		{"text": "%.1fH DAYLIGHT" % SeasonCycle.daylight_hours(season), "color": UiTheme.TEXT_DIM},
	]
	add_hero("WESTFORD POLICE -- SHIFT BRIEFING", "Shift %d" % _shift_number, chips)

## The at-a-glance operational picture the old screen never had: staffing
## and demand as headline numbers rather than five lines of prose.
func _add_summary_section() -> void:
	var core: SimulationCore = Simulation.core
	var section := add_section("OPERATIONAL SUMMARY")

	var roster_size: int = core.officer_manager.officers.size()
	var sergeants := 0
	for officer: Officer in core.officer_manager.officers.values():
		if officer.rank == GameEnums.OfficerRank.SERGEANT:
			sergeants += 1
	var unit_count: int = core.resource_manager.units.size()
	var carried: int = core.incident_manager.active_incidents.size()
	var understaffed: bool = roster_size < OfficerFactory.MINIMUM_STAFFING

	add_stat_tiles(section, [
		{"value": "%d" % roster_size, "label": "officers on duty (min %d)" % OfficerFactory.MINIMUM_STAFFING,
			"color": Color(0.90, 0.35, 0.30) if understaffed else Color(0.50, 0.85, 0.45)},
		{"value": "%d" % unit_count, "label": "patrol cars deployable", "color": UiTheme.TEXT_ACCENT},
		{"value": "%d" % sergeants, "label": "supervisors on duty", "color": UiTheme.TEXT_ACCENT},
		{"value": "%d" % carried, "label": "calls carried over",
			"color": Color(0.90, 0.65, 0.30) if carried > 0 else Color(0.50, 0.85, 0.45)},
	])
	add_dim(section, "Establishment %d -- %d on annual leave, %d in training, %d off sick." % [
		OfficerFactory.ESTABLISHMENT, OfficerFactory.ANNUAL_LEAVE, OfficerFactory.TRAINING, OfficerFactory.SICKNESS,
	])
	_add_planned_events(section)

func _add_planned_events(section: Node) -> void:
	var shift: ShiftState = Simulation.core.shift_manager.shift_state
	var found := false
	for event: EventDefinition in Simulation.core.event_manager.all_events():
		if _event_overlaps_shift(event, shift.shift_start_minute, shift.shift_end_minute):
			found = true
			add_bullet(section, "%s -- kick-off %s. Expect increased Town Centre traffic, crowding, and demand through dispersal." % [
				event.display_name, TimeFormat.clock(event.start_minute),
			])
	if not found:
		add_dim(section, "No planned events scheduled this shift.")

func _add_risks_section() -> void:
	var section := add_section("KEY RISKS")
	var risks: Array[Dictionary] = ShiftAdvisor.briefing_risks(Simulation.core)
	if risks.is_empty():
		add_dim(section, "Nothing flagged -- a routine shift on the numbers.")
		return
	for risk: Dictionary in risks:
		var severity: ShiftAdvisor.Severity = risk["severity"]
		add_flagged_row(section, ShiftAdvisor.severity_text(severity), ShiftAdvisor.severity_color(severity), String(risk["text"]))

func _add_recommendations_section() -> void:
	var section := add_section("RECOMMENDED ACTIONS")
	for item: Dictionary in ShiftAdvisor.briefing_recommendations(Simulation.core):
		add_bullet(section, String(item["text"]))

## Town conditions as meters rather than the old raw numbers line. Shown
## per district on the two variables a dispatcher can actually move:
## confidence (what the public thinks) and combined risk (what is likely
## to happen).
func _add_conditions_section() -> void:
	var section := add_section("TOWN CONDITIONS")
	for district_id in Simulation.core.district_manager.districts.keys():
		var district: DistrictState = Simulation.core.district_manager.districts[district_id]
		var def: DistrictDefinition = _world.get_district(district_id)
		var display_name: String = def.display_name if def else district_id
		var risk: float = (district.asb + district.violence + district.burglary_risk
			+ district.vehicle_crime_risk + district.theft_risk) / 5.0
		add_meter(section, display_name, "confidence %d%%" % roundi(district.community_confidence),
			district.community_confidence / 100.0, _confidence_color(district.community_confidence))
		add_meter(section, "    risk level", "%d" % roundi(risk), risk / 100.0, _risk_color(risk))

func _confidence_color(value: float) -> Color:
	if value >= 65.0:
		return Color(0.50, 0.85, 0.45)
	if value >= 45.0:
		return Color(0.90, 0.65, 0.30)
	return Color(0.90, 0.35, 0.30)

func _risk_color(value: float) -> Color:
	if value <= 25.0:
		return Color(0.50, 0.85, 0.45)
	if value <= 45.0:
		return Color(0.90, 0.65, 0.30)
	return Color(0.90, 0.35, 0.30)

func _add_intelligence_section() -> void:
	var section := add_section("INTELLIGENCE & GAPS")
	var items: Array[String] = BriefingContentFactory.starting_intelligence().duplicate()
	for item: Dictionary in Simulation.core.intelligence_manager.items:
		items.append(String(item["text"]))
	if items.is_empty():
		add_dim(section, "No intelligence held.")
	for line in items:
		add_bullet(section, line)

	var community: Array[String] = BriefingContentFactory.community_issues()
	if not community.is_empty():
		add_dim(section, "Community issues:")
		for line in community:
			add_bullet(section, line)

	var gaps: Array[String] = BriefingContentFactory.information_gaps()
	if not gaps.is_empty():
		add_dim(section, "Known information gaps:")
		for line in gaps:
			add_bullet(section, line)

## Events are scheduled by minute-of-day; a shift crossing midnight can't
## use a direct range comparison, so this samples across the shift's
## absolute-minute range instead.
func _event_overlaps_shift(event: EventDefinition, shift_start: int, shift_end: int) -> bool:
	var minute: int = shift_start
	while minute < shift_end:
		if event.is_active_at(minute % (24 * 60)):
			return true
		minute += 10
	return false

func _add_priorities_section() -> void:
	var section := add_section("PRIORITIES (pick up to %d)" % MAX_PRIORITIES)
	var row := HFlowContainer.new()
	row.add_theme_constant_override("h_separation", 6)
	row.add_theme_constant_override("v_separation", 6)
	section.add_child(row)
	for option in BriefingContentFactory.priority_options():
		var button := Button.new()
		button.text = option
		button.toggle_mode = true
		button.custom_minimum_size = Vector2(0, 46)
		button.add_theme_font_size_override("font_size", BODY_FONT)
		UiTheme.style_pill_button(button, false)
		button.toggled.connect(_on_priority_toggled.bind(option))
		row.add_child(button)
		_priority_buttons[option] = button

func _on_priority_toggled(pressed: bool, option: String) -> void:
	var button: Button = _priority_buttons[option]
	if pressed:
		if _selected_priorities.size() >= MAX_PRIORITIES:
			button.button_pressed = false # revert -- already at the cap
			return
		_selected_priorities.append(option)
	else:
		_selected_priorities.erase(option)
	# Re-style so a selected priority actually looks selected -- the old
	# screen's default Buttons gave no visible confirmation at all.
	UiTheme.style_pill_button(button, button.button_pressed)

func _add_patrol_section() -> void:
	var section := add_section("PATROL TASKING")
	add_dim(section, "Directed patrol raises visibility and suppresses crime risk at that location while the unit stays there -- but it can't respond to an incident elsewhere until reassigned.")

	for unit: PoliceUnit in Simulation.core.resource_manager.units.values():
		var crew_names: Array[String] = []
		for officer_id in unit.officer_ids:
			var officer: Officer = Simulation.core.officer_manager.get_officer(officer_id)
			if officer:
				crew_names.append(officer.officer_name)

		var row := VBoxContainer.new()
		row.add_theme_constant_override("separation", 2)
		section.add_child(row)

		var label := Label.new()
		label.text = "%s -- %s" % [unit.callsign, _join_names(crew_names)]
		label.add_theme_font_size_override("font_size", BODY_FONT)
		label.add_theme_color_override("font_color", UiTheme.TEXT_PRIMARY)
		label.autowrap_mode = TextServer.AUTOWRAP_WORD
		row.add_child(label)

		var picker := OptionButton.new()
		picker.add_item("Reserve", 0)
		var index := 1
		for location: LocationDefinition in _world.locations:
			picker.add_item(location.display_name, index)
			picker.set_item_metadata(index, location.id)
			index += 1
		picker.custom_minimum_size = Vector2(0, 46)
		picker.add_theme_font_size_override("font_size", BODY_FONT)
		row.add_child(picker)
		_patrol_pickers[unit.id] = picker

func _join_names(names: Array[String]) -> String:
	var text: String = ""
	for i in range(names.size()):
		if i > 0:
			text += ", "
		text += names[i]
	return text

func _add_reserve_section() -> void:
	var section := add_section("RESPONSE RESERVE")
	add_dim(section, "How many deployable units to keep back for immediate response, rather than committing to patrol tasks.")
	_reserve_spinbox = SpinBox.new()
	_reserve_spinbox.min_value = 0
	_reserve_spinbox.max_value = Simulation.core.resource_manager.units.size()
	_reserve_spinbox.value = 2
	_reserve_spinbox.custom_minimum_size = Vector2(140, 46)
	section.add_child(_reserve_spinbox)

func _on_confirm_pressed() -> void:
	for unit_id in _patrol_pickers.keys():
		var picker: OptionButton = _patrol_pickers[unit_id]
		var location_id = picker.get_item_metadata(picker.selected)
		if location_id != null and location_id != "":
			Simulation.commands().set_directed_patrol(unit_id, location_id)
	Simulation.core.confirm_briefing(_selected_priorities, int(_reserve_spinbox.value))
	confirmed.emit()
